-- Production-like order inbox simulation for local/staging demos.
-- Safe to re-run: demo rows are upserted by id.

insert into public.orders (
  id,
  restaurant_id,
  status,
  order_channel,
  delivery_provider,
  payment_status,
  external_provider,
  external_order_id,
  external_status,
  external_payload,
  customer_name,
  customer_note,
  fulfillment_mode,
  delivery_address,
  table_number,
  total_items,
  total_cop,
  whatsapp_message,
  whatsapp_link,
  created_at
) values
  (
    'ord_prod_sim_001',
    'brasas-sazon',
    'pending',
    'cartamago',
    'didi_food',
    'pending',
    'didi_food',
    'didi-draft-001',
    'draft_created',
    '{"source":"cartamago","handoff":"didi_food","sandbox":true}'::jsonb,
    'Laura Torres',
    'Confirmar disponibilidad antes de enviar a DiDiFood',
    'didi_food',
    'Cra 45 #12-30, apto 402',
    '',
    4,
    104000,
    'Hola, quiero encargar por DiDiFood desde CartaMago: 1 pollo asado, 2 limonadas y 1 maduro.',
    'https://wa.me/573104217941?text=Pedido%20DiDiFood%20simulado',
    now() - interval '7 minutes'
  ),
  (
    'ord_prod_sim_002',
    'brasas-sazon',
    'confirmed',
    'cartamago',
    'local',
    'not_required',
    null,
    null,
    null,
    '{"source":"cartamago","route":"local_delivery","sandbox":true}'::jsonb,
    'Andres Molina',
    'Pagar en efectivo, enviar cambio de 100000',
    'local_delivery',
    'Calle 18 #7-42, Barrio Centro',
    '',
    3,
    78000,
    'Hola, quiero domicilio local: 2 churrascos y 1 jugo en agua.',
    'https://wa.me/573104217941?text=Pedido%20domicilio%20local%20simulado',
    now() - interval '22 minutes'
  ),
  (
    'ord_prod_sim_003',
    'brasas-sazon',
    'preparing',
    'whatsapp',
    'none',
    'not_required',
    null,
    null,
    null,
    '{"source":"operator","route":"pickup","sandbox":true}'::jsonb,
    'Sofia Rojas',
    'Recoge en 25 minutos',
    'pickup',
    '',
    '',
    2,
    52000,
    'Hola, paso a recoger: 1 bandeja paisa y 1 limonada natural.',
    'https://wa.me/573104217941?text=Pedido%20recoger%20simulado',
    now() - interval '38 minutes'
  ),
  (
    'ord_prod_sim_004',
    'brasas-sazon',
    'ready',
    'cartamago',
    'none',
    'not_required',
    null,
    null,
    null,
    '{"source":"qr_table","route":"table","sandbox":true}'::jsonb,
    'Mesa 6',
    'Llevar ají aparte',
    'table',
    '',
    '6',
    5,
    130000,
    'Hola, pedido para mesa 6: 2 puntas de anca, 2 sopas de pollo y 1 gaseosa.',
    'https://wa.me/573104217941?text=Pedido%20mesa%206%20simulado',
    now() - interval '51 minutes'
  ),
  (
    'ord_prod_sim_005',
    'brasas-sazon',
    'delivered',
    'cartamago',
    'local',
    'not_required',
    null,
    null,
    null,
    '{"source":"cartamago","route":"local_delivery","sandbox":true}'::jsonb,
    'Camilo Perez',
    '',
    'local_delivery',
    'Av 2 #9-11',
    '',
    2,
    52000,
    'Hola, domicilio local: 1 pollo apanado y 1 papas a la francesa.',
    'https://wa.me/573104217941?text=Pedido%20entregado%20simulado',
    now() - interval '2 hours'
  ),
  (
    'ord_prod_sim_006',
    'brasas-sazon',
    'cancelled',
    'didi_food',
    'didi_food',
    'cancelled',
    'didi_food',
    'didi-cancelled-006',
    'cancelled_by_customer',
    '{"source":"didi_food","reason":"customer_cancelled","sandbox":true}'::jsonb,
    'Natalia Gomez',
    'Pedido cancelado desde proveedor',
    'didi_food',
    'Calle 30 #8-80',
    '',
    1,
    26000,
    'Pedido DiDiFood cancelado: 1 salchipapas.',
    'https://wa.me/573104217941?text=Pedido%20cancelado%20simulado',
    now() - interval '3 hours'
  )
on conflict (id) do update set
  status = excluded.status,
  order_channel = excluded.order_channel,
  delivery_provider = excluded.delivery_provider,
  payment_status = excluded.payment_status,
  external_provider = excluded.external_provider,
  external_order_id = excluded.external_order_id,
  external_status = excluded.external_status,
  external_payload = excluded.external_payload,
  customer_name = excluded.customer_name,
  customer_note = excluded.customer_note,
  fulfillment_mode = excluded.fulfillment_mode,
  delivery_address = excluded.delivery_address,
  table_number = excluded.table_number,
  total_items = excluded.total_items,
  total_cop = excluded.total_cop,
  whatsapp_message = excluded.whatsapp_message,
  whatsapp_link = excluded.whatsapp_link,
  created_at = excluded.created_at;

insert into public.order_items (
  id,
  order_id,
  product_id,
  product_name,
  quantity,
  unit_price_cop,
  line_note,
  sort_order
) values
  ('itm_prod_sim_001_01', 'ord_prod_sim_001', 'pollo-entero', '1 Pollo asado al carbon', 1, 26000, '', 10),
  ('itm_prod_sim_001_02', 'ord_prod_sim_001', 'limonada-natural', 'Limonada natural', 2, 26000, 'Bien fria', 20),
  ('itm_prod_sim_001_03', 'ord_prod_sim_001', 'maduro-entero', 'Maduro entero', 1, 26000, '', 30),
  ('itm_prod_sim_002_01', 'ord_prod_sim_002', 'churrasco', 'Churrasco 300 gr', 2, 26000, 'Termino medio', 10),
  ('itm_prod_sim_002_02', 'ord_prod_sim_002', 'jugo-agua', 'Jugo en agua', 1, 26000, 'Mora', 20),
  ('itm_prod_sim_003_01', 'ord_prod_sim_003', 'bandeja-paisa', 'Bandeja paisa', 1, 26000, '', 10),
  ('itm_prod_sim_003_02', 'ord_prod_sim_003', 'limonada-natural', 'Limonada natural', 1, 26000, '', 20),
  ('itm_prod_sim_004_01', 'ord_prod_sim_004', 'punta-anca', 'Punta de anca 300 gr', 2, 26000, 'Bien asada', 10),
  ('itm_prod_sim_004_02', 'ord_prod_sim_004', 'sopa-pollo', 'Sopa de pollo', 2, 26000, '', 20),
  ('itm_prod_sim_004_03', 'ord_prod_sim_004', 'jugo-agua', 'Jugo en agua', 1, 26000, 'Mango', 30),
  ('itm_prod_sim_005_01', 'ord_prod_sim_005', 'pollo-apanado', '1 Pollo apanado', 1, 26000, '', 10),
  ('itm_prod_sim_005_02', 'ord_prod_sim_005', 'papas-francesa', 'Papas a la francesa', 1, 26000, '', 20),
  ('itm_prod_sim_006_01', 'ord_prod_sim_006', 'salchipapas', 'Salchipapas', 1, 26000, '', 10)
on conflict (id) do update set
  product_id = excluded.product_id,
  product_name = excluded.product_name,
  quantity = excluded.quantity,
  unit_price_cop = excluded.unit_price_cop,
  line_note = excluded.line_note,
  sort_order = excluded.sort_order;

select 'production order simulation loaded' as result;
